# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IUWpanYRV9t_OllVAYIJpjK2uEQU5yEJ
"""

class Transform3D:
    def __init__(self, R, p):
        # Guarda R y p por separado, pero arma también la matriz 4x4 completa
        # para que sea fácil multiplicar transformaciones encadenadas.
        ...

    def inv_analytic(self):
        # Aplica exactamente lo que dedujimos en la Tarea B:
        # R' = R.T, p' = -R.T @ p
        # Es la fórmula que "sabe" que T es una transformación rígida.
        ...

    def inv_generic(self):
        # np.linalg.inv() NO sabe que T es rígida — resuelve el sistema
        # lineal 4x4 completo como si fuera una matriz cualquiera.
        # Sirve solo para comparar precisión y velocidad.
        ...